# Importance function in pytorch

In [3]:
import torch

### Compute with tensor

In [4]:
# Create tensor
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y= 5 
squared_diff = (x-y)**2
print(f'x:\n {x}')
print(f'y= {y}')
print(f'Squared_diff: {squared_diff}')

x:
 tensor([1., 2., 3., 4.])
y= 5
Squared_diff: tensor([16.,  9.,  4.,  1.])


### Mean Squared Error

In [2]:

# Create tensor
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = torch.tensor([5.0, 5.0, 5.0, 5.0])

# Compute MSE 
loss_fn = torch.nn.MSELoss()
mse = loss_fn(x,y)

print(f'x:\n {x}')
print(f'y= {y}')
print(f'mse: {mse}')

x:
 tensor([1., 2., 3., 4.])
y= tensor([5., 5., 5., 5.])
mse: 7.5


### Concatenate 

In [6]:
x = torch.tensor([[1, 2],
                  [3, 4]])
y = torch.tensor([[3, 4],
                  [5, 6]])

# Concat tensors along the first dim = 0 
tensor_dim_0  =torch.cat((x,y),dim= 0)
print(f'Tensor_dim_0:\n{tensor_dim_0}')

# Concat tensors along the second dim = 1
tensor_dim_1  =torch.cat((x,y),dim= 1)
print(f'Tensor_dim_1:\n{tensor_dim_1}')

Tensor_dim_0:
tensor([[1, 2],
        [3, 4],
        [3, 4],
        [5, 6]])
Tensor_dim_1:
tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])


### Argument Max 
Find  a index value with the greatest value
(Tìm giá trị index lấy đúng 1 cái lớn nhất đầu tiên  mà ở đó có giá trị lớn nhất) 

-You can using argmax to find one hot encode to imporve speed 


In [10]:
# Create a 3x2 tensor
data = torch.randint(low =0 ,high = 9,size = (3,2))
print(f'data:\n{data}')

# Compute argmax across the rows with dim = 0 
argmax_dim_0 =torch.argmax(data,dim=0)
print(f'argmax with dim = 0 :\n{argmax_dim_0}')


# Compute argmax across the columns with dim = 1 
argmax_dim_1 =torch.argmax(data,dim=1)
print(f'argmax with dim = 0 :\n{argmax_dim_1}')

data:
tensor([[2, 7],
        [2, 3],
        [0, 2]])
argmax with dim = 0 :
tensor([0, 0])
argmax with dim = 0 :
tensor([1, 1, 1])


### Gradient computation ( Đạo hàm)

In [12]:
# Create a tesor
x = torch.tensor(2.0,requires_grad=True)

# Operation
y= x ** 2 
z =3*y + 2
print(f'z: {z}')

# Backpropagate to compute gradients
z.backward()

# Print the gradient. dz/dx at  x=2.0
print(f"Gradient of z w.r.t  x: {x.grad}")

z: 14.0
Gradient of z w.r.t  x: 12.0


### Linear layer

In [14]:
import torch.nn as nn 
# Create a linear layer
# first parameter is input layer Second parameter is output layer
linear = nn.Linear(1,1)

# Set values 
linear.bias.data = torch.Tensor([0.04])
linear.weight.data = torch.Tensor([-0.34])

print(f'b - {linear.bias}')
print(f'w - {linear.weight}')

# Loss function and optimizer
loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(linear.parameters(),lr=0.01)

b - Parameter containing:
tensor([0.0400], requires_grad=True)
w - Parameter containing:
tensor([-0.3400], requires_grad=True)
